name: Metrics Update
on:
  schedule: [{cron: "0 * * * *"}]
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: warioddly
          base: header, activity, community, repositories, metadata
          config_display: large
          config_padding: 0, 4 + 2%
          config_timezone: Asia/Bishkek
          plugin_languages: yes
          plugin_languages_colors: github
          plugin_languages_limit: 8
          plugin_languages_recent_days: 14
          plugin_languages_recent_load: 300
          plugin_languages_sections: most-used
          plugin_languages_threshold: 0%
          plugin_lines: yes
          plugin_notable: yes
          plugin_leetcode: yes
          plugin_leetcode_user: warioddly
          plugin_leetcode_sections: solved, skills, recent
          plugin_contributors: yes
          plugin_contributors_base: ""
          plugin_contributors_head: master
          plugin_contributors_ignored: bot
          plugin_contributors_contributions: yes
          plugin_stars: тщ
          plugin_stars_limit: 4
